site_name: Test Mkdocs

# Repository
repo_name: 'Briffou/mkdocs_test'
repo_url: 'https://github.com/Briffou/mkdocs_test'

theme:
  name: 'material'
  language: 'fr'
  logo: 'images/GIREF_renverse.png'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/Briffou'
